<?php

namespace AppBundle\Repository;

/**
 * MedewerkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedewerkerRepository extends \Doctrine\ORM\EntityRepository
{
}
